backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    description: "Hi Danny"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
